#!/usr/bin/env bash
set -euo pipefail

# provision-board.sh — Set up a new customer board on a Hetzner VPS
#
# Usage:
#   ./scripts/provision-board.sh <customer-slug> <customer-name> <telegram-bot-token>
#
# Example:
#   ./scripts/provision-board.sh acme-corp "Acme Corporation" "123456:ABC-DEF..."
#
# Prerequisites:
#   - BoardOS repo cloned to /opt/board-os (or wherever BOARD_OS_ROOT points)
#   - Node.js 20+ installed
#   - Docker installed and running
#   - sqlite3 available

BOARD_OS_ROOT="${BOARD_OS_ROOT:-/opt/board-os}"
CUSTOMER_SLUG="${1:?Usage: provision-board.sh <customer-slug> <customer-name> <telegram-bot-token>}"
CUSTOMER_NAME="${2:?Usage: provision-board.sh <customer-slug> <customer-name> <telegram-bot-token>}"
TELEGRAM_TOKEN="${3:?Usage: provision-board.sh <customer-slug> <customer-name> <telegram-bot-token>}"

WORKSPACE_DIR="${BOARD_OS_ROOT}/groups/telegram_${CUSTOMER_SLUG}"
TEMPLATE_DIR="${BOARD_OS_ROOT}/templates/customer-workspace"
BRAIN_DB="${WORKSPACE_DIR}/brain/brain.db"

echo "═══════════════════════════════════════════"
echo "  BoardOS — Provisioning: ${CUSTOMER_NAME}"
echo "═══════════════════════════════════════════"
echo ""

# --- Step 1: Create workspace from template ---
echo "→ Creating workspace at ${WORKSPACE_DIR}..."
if [ -d "${WORKSPACE_DIR}" ]; then
  echo "  ⚠ Workspace already exists. Aborting to prevent overwrite."
  echo "  Remove ${WORKSPACE_DIR} first if you want to start fresh."
  exit 1
fi

cp -r "${TEMPLATE_DIR}" "${WORKSPACE_DIR}"
echo "  ✓ Workspace created from template"

# --- Step 2: Customize SOUL.md ---
echo "→ Customizing SOUL.md..."
sed -i.bak \
  -e "s/\[Customer Name\]/${CUSTOMER_NAME}/g" \
  -e "s/\[Industry\]/[To be configured during onboarding]/g" \
  "${WORKSPACE_DIR}/SOUL.md"
rm -f "${WORKSPACE_DIR}/SOUL.md.bak"
echo "  ✓ SOUL.md personalized"

# --- Step 3: Initialize Brain database ---
echo "→ Initializing Brain database..."
sqlite3 "${BRAIN_DB}" <<'SQL'
CREATE TABLE IF NOT EXISTS facts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  source TEXT,
  confidence REAL DEFAULT 1.0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT NOT NULL,
  decision TEXT NOT NULL,
  rationale TEXT,
  decided_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  revisit_at DATETIME
);

CREATE TABLE IF NOT EXISTS insights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  insight TEXT NOT NULL,
  evidence TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_facts_category ON facts(category);
CREATE INDEX IF NOT EXISTS idx_facts_key ON facts(key);
CREATE INDEX IF NOT EXISTS idx_decisions_topic ON decisions(topic);
CREATE INDEX IF NOT EXISTS idx_insights_category ON insights(category);
SQL
echo "  ✓ Brain database initialized"

# --- Step 4: Create .env file ---
echo "→ Creating .env..."
ENV_FILE="${BOARD_OS_ROOT}/.env"
if [ ! -f "${ENV_FILE}" ]; then
  cat > "${ENV_FILE}" <<EOF
# BoardOS Configuration
# Generated by provision-board.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Telegram Bot
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}

# Customer: ${CUSTOMER_NAME} (${CUSTOMER_SLUG})
CUSTOMER_SLUG=${CUSTOMER_SLUG}
CUSTOMER_NAME=${CUSTOMER_NAME}

# Anthropic API Key (REQUIRED — RTB managed, never shared with customers)
ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:-sk-ant-REPLACE_ME}

# Model Routing — controls cost vs quality tradeoff
# Primary model: used for complex work (strategy, multi-step tasks, creative)
CLAUDE_MODEL=claude-sonnet-4-20250514
# Fast model: used by SDK for lightweight operations (edits, quick lookups, tool calls)
CLAUDE_SMALL_FAST_MODEL=claude-haiku-3-5-20241022

# Container settings
CONTAINER_MEMORY_LIMIT=512m
CONTAINER_CPU_LIMIT=1.0
EOF
  echo "  ✓ .env created"
else
  echo "  ⚠ .env already exists — not overwriting"
  echo "  Add these to your .env if needed:"
  echo "    TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}"
  echo "    CUSTOMER_SLUG=${CUSTOMER_SLUG}"
fi

# --- Step 5: Set permissions ---
echo "→ Setting permissions..."
chmod -R 755 "${WORKSPACE_DIR}"
chmod 600 "${ENV_FILE}" 2>/dev/null || true
echo "  ✓ Permissions set"

# --- Done ---
echo ""
echo "═══════════════════════════════════════════"
echo "  ✓ Board provisioned for ${CUSTOMER_NAME}"
echo "═══════════════════════════════════════════"
echo ""
echo "Next steps:"
echo ""
echo "  1. Set the RTB Anthropic API key in .env:"
echo "     ANTHROPIC_API_KEY=sk-ant-..."
echo "     (Use RTB's managed key — never a customer's key)"
echo ""
echo "  Model routing (already configured):"
echo "     CLAUDE_MODEL=claude-sonnet-4  (complex work)"
echo "     CLAUDE_SMALL_FAST_MODEL=claude-haiku-3.5  (lightweight ops)"
echo ""
echo "  2. Configure DNS:"
echo "     Point ${CUSTOMER_SLUG}.runtheboard.ai → this VPS IP"
echo ""
echo "  3. Set up the Telegram bot:"
echo "     - Talk to @BotFather on Telegram"
echo "     - Bot token is already in .env"
echo "     - Send /start to your bot to initialize"
echo ""
echo "  4. Register the customer group in BoardOS:"
echo "     Use the operator console to register the Telegram chat"
echo ""
echo "  5. Complete onboarding:"
echo "     - Update SOUL.md with customer's industry and preferences"
echo "     - Fill in MEMORY.md with known business context"
echo "     - Schedule morning brief and weekly report"
echo ""
echo "  6. Start BoardOS:"
echo "     cd ${BOARD_OS_ROOT} && npm start"
echo ""
